# Generated by Django 3.0.7 on 2020-06-17 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('ticker_symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('registered_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('index_key', models.CharField(blank=True, max_length=50, null=True)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharesOutstanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shares_outstanding', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_outstanding', to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='PublicFloat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('public_float', models.DecimalField(decimal_places=2, max_digits=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_float', to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Company10kRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_focus', models.CharField(max_length=4)),
                ('annual_report', models.BooleanField(default=False)),
                ('transition_report', models.BooleanField(default=False)),
                ('fy_end_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_10k', to='companies.Company')),
            ],
        ),
    ]
